### PR TITLE
Make Debezium Connector compatible with Oracle 12.1.0.2.0 and earlier version

### PR DESCRIPTION
**Pull request by ekhan128**
The issue was logged in DBZ-1313: RE: https://groups.google.com/d/msgid/debezium/7f73b99d-0d8e-4e53-b4d5-f2eee756acd6%40googlegroups.com

Debezium is unable to work with Oracle 12.1.0.2.0. Produces ERROR as below:

ERROR Producer failure (io.debezium.pipeline.ErrorHandler:36)
java.lang.RuntimeException: java.lang.NoSuchMethodError: oracle.streams.XStreamUtility.convertSCNToPosition(Loracle/sql/NUMBER;I)[B

Here is the issue described at the Debezium Group by Chris Cranford:
Oracle 12.1 (RC1) version expects a single argument to be passed where-as the 12.2 (RC2) version expects two arguments. Ironically our code current attempts to pass two arguments, which would lead to this exception if you were using the 12.1.0.2 versions of the libraries. This at least appears like a compatibility issue. It would appears that using the ojdbc8.jar and xstreams.jar from 12.2.0.1 resolves the issue; however I'm not sure if those are necessarily compatible with your Oracle 12.1.0.2 (RC1) installation.

Please implement the required code change so that Debezium Connector for Oracle version 12.1 (RC1) and earlier works similarly to Oracle version 12.2 (RC2)

CC: @gunnarmorling

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hum, I'm a bit puzzled by this one, @ekhan128 :)

You'd file a pull request for actually implementing this change. The requirement itself is already tracked in JIRA. If you're interested in contributing the required code change let us know. Thanks!

**Comment by ekhan128** [comment]
Hi Gunnar,

I actually wasn’t sure why I was creating a PR as I wasn't making any code change.

You mentioned in the Group discussion

“Hey @ekhan128, something isn't quite right with this PR, it doesn't target the debezium/master branch and pulls in lots of unrelated commits. Can you create a new PR which targets debezium/master and has your fork as the source? Thanks!”

With my no experience :-( in this space, I thought you asked me to do what I did.

In any case- I guess I am curious, what I do now and what happens next. Will someone pick up the Jira issue and resolve the Oracle compatibility issue?

Thanks so much and apologies for my confusion and lack of my understanding.

Ehsan

**Comment by ekhan128** [comment]
Hi Gunnar,

Coming back to an old issue. I am not sure what to do next from here. Will there be a dbzium version which will work with Oracle 12.1.0.2 or earlier. I know I wasn't able to do what you asked because of my lack of understanding.
